### ISSUE TITLE
useless plunker

### ISSUE THREAD

**Issue by robbiemu** [OasisDigital/rxjs-system-bundle#1]
this looks tempting ... but your plunker example is empty - it doesn't even load RxJS. What does the import statement look like?

You should have a hello-world in the component like:
```
$scope.Output = 'before'

let myVar
Rx.Observable.of(myVar)
  .subscribe(function(x) { $scope.Output = x });

setTimeout(function(){ myVar = 'after'}, 2000)
```

**Comment by kylecordes** [comment]
Hello, thanks for the comments. The Plunkr did use RxJS, indirectly - Angular depends on RxJS and loads it. To make it more obvious, I have edited the Plunks to also directly use RxJS. It shows the proper import format, which is the same as seen in the Angular documentation, same as with Angular CLI.

**Comment by robbiemu** [comment]
Hi Kyle,
Thanks for overlooking the post title :) I was .. definitely not thinking about it when I wrote that. It *is* a lackluster plunker though.  And it remains that way, did you remember to save your changes? (we are talking about https://plnkr.co/edit/Fy0jvu?p=preview right?)

I see:
### app.ts
```ts
//our root app component
import {Component, NgModule} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@Component({
//...
```

### main.ts
```ts
//main entry point
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {AppModule} from './app';

platformBrowserDynamic().bootstrapModule(AppModule)
```

there's obviously no import statement yet. :)

**Comment by kylecordes** [comment]
Ah - I had missed the "Freeze" button. Take a look now, at app.ts.

**Comment by robbiemu** [comment]
much thanks :)
