### ISSUE TITLE
Path resolution fails when used as local npm package

### ISSUE THREAD

**Issue by kkganesan** [OasisDigital/rxjs-system-bundle#2]
package.json
`rxjs-system-bundle: '5.1.1'`

system.config.js
```
var map = {
...
'rxjs': 'node_modules/rxjs-system-bundle/Rx.system.js'
}

var packages = {
...
'rxjs': { defaultExtension: false }
}

var bundles = {
      'rxjs': [
          "rxjs",
          "rxjs/*",
          "rxjs/operator/*",
          "rxjs/observable/*",
          "rxjs/scheduler/*",
          "rxjs/symbol/*",
          "rxjs/add/operator/*",
          "rxjs/add/observable/*",
          "rxjs/util/*"
        ],
...
}
```

When the above configuration used in building lazy loaded dynamic bundles
https://github.com/systemjs/builder/blob/master/docs/api.md#builderbundletree-outfile-options

Throws build error 
```
{ [Error: Error on fetch for node_modules/rxjs-system-bundle/Rx.system.js/Observable.js at 
file:///... node_modules/rxjs-system-bundle/Rx.system.js/Observable.js
        Loading node_modules/@angular/core/bundles/core.umd.min.js
        Loading app/app.component.js
        ENOENT: no such file or directory, open '... node_modules\rxjs-system-bundle\Rx.system.js\Observable.js']
  originalErr:
   { [Error: ENOENT: no such file or directory, open '... node_modules\rxjs-system-bundle\Rx.system.js\Observable.js']
```

Thoughts ?

**Comment by kylecordes** [comment]
What does you import statement (in your application code) look like?

**Comment by kkganesan** [comment]
Destructured...

`import { Observable } from 'rxjs/Observable';
import { Observer } from 'rxjs/Observer';
...

`

**Comment by kylecordes** [comment]
The imports looks totally normal. But I think I see the problem. To load a bundle using SystemJS, you need to use the `bundle` setting, not just the `map`. Look at the README for this repo for an example.

I don't think there is anything to fix in the contents of the bundle, so I'll resolve the issue for now.
