### ISSUE TITLE
Version 6 is missing the js files

### ISSUE THREAD

**Issue by timruhle** [OasisDigital/rxjs-system-bundle#5]
Installing via npm or download https://registry.npmjs.org/rxjs-system-bundle/-/rxjs-system-bundle-6.0.0.tgz is missing all of the `js` and `map` files.

**Comment by kylecordes** [comment]
Thanks - it looks like the auto publish mechanism went awry on V6. Will investigate when I can.

**Comment by kylecordes** [comment]
For various yak shaving reasons, I probably won't have a chance to attack this until after it is possible to use Angularfire2 with RxJS 6...  that is when I will need this bundle figured out, hopefully that will arrive in not too many days.

(I am currently using Angular 6 which works fine with the current latest Angularfire2... with RxJS 5 forward-compat.   Angular's dependencies mention RxJS 6, but experimentally Angular 6 works fine with 5-forward-compat.)

**Comment by mlakmal** [comment]
if it helps anyone, i have added v6 support in below repo.

https://github.com/mlakmal/rxjs-system-bundle

**Comment by kylecordes** [comment]
@mlakmal PR? :-)

**Comment by kylecordes** [comment]
Thank you, I will update the token in the next couple days.

**Comment by kylecordes** [comment]
Done. Hopefully the automatic process will now do its job successfully again.
